### ISSUE TITLE
Mark old typer-builds as broken (or depending on click<8.0)

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/typer-feedstock#5]
Before #4, the `click` dependency had no upper bound, leading to the fact that most downstream dependencies (e.g. spacy) are now broken, because the resolver prefers the unrestricted typer build, that breaks with the newest click 8.0.0, which has apparently removed `click._bashcomplete` (spacy [depends](https://github.com/conda-forge/spacy-feedstock/blob/master/recipe/meta.yaml#L50) on `typer >=0.3.0,<0.4.0`).

```
  File "/home/conda/[...]/site-packages/allennlp/__init__.py", line 18, in <module>
    import transformers, spacy, torch, numpy  # noqa
  File "/home/conda/[...]/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/home/conda/[...]/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/home/conda/[...]/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/home/conda/[...]/site-packages/typer/__init__.py", line 31, in <module>
    from .main import Typer, run
  File "/home/conda/[...]/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/home/conda/[...]/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

Installed versions (example [CI run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=333031&view=results) from https://github.com/conda-forge/allennlp-feedstock/pull/28):
```
The following NEW packages will be INSTALLED:

    [...]
    click:                         8.0.1-py36h5fab9bb_0         conda-forge
    [...]
    python:                        3.6.13-hffdb5ce_0_cpython    conda-forge
    [...]
    spacy:                         3.0.6-py36h706143c_0         conda-forge
    spacy-legacy:                  3.0.5-pyhd8ed1ab_0           conda-forge
    spacy-model-en_core_web_sm:    3.0.0-pyhd8ed1ab_1           conda-forge
    [...]
    typer:                         0.3.1-py_0                   conda-forge
    [...]
```

CC @conda-forge/typer @conda-forge/spacy

**Comment by h-vetinari** [comment]
Ping @conda-forge/typer @conda-forge/core
This is a pretty serious regression IMO, because it makes current downstream packages (e.g. spacy) uninstallable.

**Comment by adrianeboyd** [comment]
Hmm, I think that that result from the dependency resolver must be related to some other requirement or setting in `allennlp`? If I create a brand new environment and run `conda install -c conda-forge spacy`, I see:

```none
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  spacy              conda-forge/linux-64::spacy-3.0.6-py39h5472131_0
  typer              conda-forge/noarch::typer-0.3.2-pyhd8ed1ab_0
```

I rebuilt spacy v3.0.6 to double-check and spacy by itself does not result in this configuration: https://github.com/conda-forge/spacy-feedstock/pull/108

In the spacy bug tracker there have been a few reports related to the typer/click issue from people whose envs have gotten out-of-sync due to pip (a separate package install upgrades click and breaks spacy), but we haven't had any reports about this in conda, which would be surprising if this were the default behavior for new spacy installs.

Not to say that this isn't an issue, but I'm not sure how the dependency resolver ends up with that set of packages, since it doesn't seem to be just related to a preference for unrestricted builds?

**Comment by adrianeboyd** [comment]
I take it back, we have the same problem here (and this is only minimally different installing spacy itself, so this is weird): https://github.com/conda-forge/spacy-legacy-feedstock/pull/5
